### ISSUE TITLE
HTML5 Support

### ISSUE THREAD

**Issue by raeleus** [rockbite/talos#45]
Hello,

It appears to me that Talos is not ready for HTML5 support (and also mobile support). Besides missing the typical gwt.xml files, the runtime project depends on Java AWT and other uncompilable classes. Please see the following:
https://github.com/rockbite/talos/blob/master/runtimes/talos-libgdx/src/com/talosvfx/talos/runtime/ScopePayload.java#L24
https://github.com/rockbite/talos/blob/master/runtimes/talos-libgdx/src/com/talosvfx/talos/runtime/script/ScriptCompiler.java#L24

Is this in the roadmap for the project? This is an absolute necessity if you want Talos to be considered as a full replacement for the vanilla particle system. Thank you.

**Comment by Tom-Ski** [comment]
Hey @raeleus. Its mostly supported now on web on the talos-3d branch, which is the future branch. Both runtimes and editor itself are compatible, with features to be ignored if they are not possible (like the script compiler).
