### ISSUE TITLE
ParticleEmitterBox2D Implementation

### ISSUE THREAD

**Issue by blaedde** [rockbite/talos#65]
Hi There

Is it possible to add the ParticleEmitterBox2D to a Particle Effect Descriptor / Effect Instance ?

https://libgdx.badlogicgames.com/ci/nightlies/docs/api/com/badlogic/gdx/physics/box2d/graphics/ParticleEmitterBox2D.html

Regards
Blaedde

**Comment by Tom-Ski** [comment]
This is out of the scope here. You can make a wrapper easily enough that just updates its position based on the body.
