### ISSUE TITLE
Discord link in README and website homepage is broken

### ISSUE THREAD

**Issue by Frosty-J** [rockbite/talos#69]
Also tested via Browserling to confirm I'm not IP-banned. No dice.

![This invite may be expired, or you might not have permission to join.](https://user-images.githubusercontent.com/60154347/129461882-11936c09-a687-413a-a7f8-238fc3aa4091.png)

Not sure there's much hope of it getting fixed on the website when its footer says copyright 2019 and has placeholder anchor links for the Instagram, Pinterest and Behance pages, but this repository looks alive enough.

**Comment by Tom-Ski** [comment]
Fixed
