### ISSUE TITLE
Rendering particles in Libgdx after export is extremely small

### ISSUE THREAD

**Issue by cypai** [rockbite/talos#76]
I followed the instructions at https://github.com/rockbite/talos/wiki/Libgdx-Runtime to import the generated particle effect into a Libgdx game. At first I thought I messed up the rendering because I couldn't see any particle effects at all, but I eventually found out that it was just extremely tiny. As a comparison, I imported the fire example into my game, and the fire effect rendered at the same size that the Talos editor would show it at Grid 30, which is basically barely visible. I have it currently rendering in its own batch.begin/end, so other rendering code shouldn't be getting involved.

The demo code at https://github.com/rockbite/talos/blob/master/runtimes/talos-libgdx/test/com/talosvfx/talos/runtime/test/TalosDemo.java uses a strange value for the Viewport. Clearly I'm missing something here, how should I properly configure SpriteBatchParticleRenderer?

Libgdx version is 1.9.14
Talos Libgdx Runtime version is 1.4.0

**Comment by Tom-Ski** [comment]
That isn't a strange value for a viewport. 10, 10 world units. You probably have a viewport/camera setup that is using much larger units. Talos is using world units for all the values, so you should have your viewport also setup in the same space
