### ISSUE TITLE
Particle Rotation During Runtime 

### ISSUE THREAD

**Issue by theovier** [rockbite/talos#79]
Hi there,

I want to rotate a complete `ParticleEffectInstance` dynamically by a certain degree during runtime in a libGDX program.
What would be the best way to achieve this?

Thanks

**Comment by Tom-Ski** [comment]
If you expose rotation by a global value, you can then set the global value for that effect using its ScopePayload. Thats usually the best way to expose "controls" for any part of the effect

**Comment by theovier** [comment]
Thanks for the swift response!
That did the trick. For future reference, to set a global value via the ScopePayload, one has to use the `setDynamicValue` method, e.g., `effect.scope.setDynamicValue(0, 90f)`.

Thanks again :)
